### ISSUE TITLE
RFC for Pizzly 2.0: We want your input

### ISSUE THREAD

**Issue by rguldener** [NangoHQ/Pizzly#263]
Hey Pizzly community,

we are Bastien and Robin, the new stewards of Pizzly 🐻

Pizzly became popular because it is one of the fastest and simplest ways to get started with APIs that use OAuth. Currently Pizzly has some issues with the latest version of node and the code has been largely unmaintained for 1+ year.

We want to fix and improve Pizzly, but for this we need your help:
- Do you have experience with the Pizzly code base & features? We would love to talk to you!
- Are you a current or former user of Pizzly? We would like to understand:
    - How do you use Pizzly? (which APIs, how does it fit into your app etc.)
    - How do you host Pizzly? How happy are you with this setup?
    - What do you like most about it?
    - What annoys you/gets in the way?
- Anything else you wanted to share with us for the future of Pizzly?

Your inputs will be super valuable to shape the future of this project.

If you want to get involved with contributing and designing the next version please join our [Slack community](https://nango.dev/slack): We would be happy to have you as part of the core team.

We look forward to hearing from you in the comments and building a better Pizzly together!

**Comment by rcknr** [comment]
Hi Robin,

It's great that you have convinced guys at Bearer to revive the repository! I have also reached out to offer my help in maintaining Pizzly but they said they had decided to archive it.
There were a couple of issues/PRs before the project got archived. I think it makes sense to look over these for some feedback first. Here are my personal observations about Pizzly:
- It'd be great to have multiple APIs supported within one provider and organize them in one filterable list
- Also would be great to add and maintain guidance for creating app credentials for each provider
- Could use alternative storage backend to decrease running cost
I'm glad that the project is getting a new start and hope it stays active. I'd be glad to help where I can.

Cheers,

Sergii

**Comment by bastienbeurier** [comment]
Thank you for chiming in and offering to contribute!

I will go through previous issues & PRs as you advised. Also, feel free to create issues (or even PRs) if you want some of your suggestions to be implemented soon.

We are currently focusing on refreshing/fixing the repo for local development, but it would be great to have your input as we move towards improving it. 

We've created a Slack room dedicated to Pizzly in our [Slack community](https://nango.dev/slack) in case you want to follow Pizzly news more closely and discuss ongoing work. We will ask the community's opinion and share plans on a regular basis there.

**Comment by mikestaub** [comment]
1. prioritize proxy as that is how 80% of dev will likely use this tool
2. do NOT rewrite. At least not until the API surfaces are solid and the tool has more traction. This techt debt should not be paid at this time.
3. in-code. This is a dev tool, no need to maintain a UI, someone else can do that
4. Just create a docker image. This should not be prioritized at this stage

**Comment by bastienbeurier** [comment]
Thank you for your input @mikestaub!

1. Understood, we've heard this from other Pizzly as well!
2. After taking a 1st pass at the codebase and finding it hard to maintain, we actually already took a pass at the rewrite last week. We will release it today and plan to have feature parity next Monday.
3. Great, this alines with the rest of the feedback as well.
4. Agreed, we've done this as part of the rewrite actually.

**Comment by Simcon** [comment]
100% what @mikestaub says. 

It should be completely configurable in code so configs can be versioned.

**Comment by MattRiddell** [comment]
1. Agreed with @mikestaub 
2. I could go both ways on this. If you're being significantly slowed down by working on a codebase that doesn't match your internal tooling, it may be worth it. Hah just saw your comment. Cool.
3. Hmm, I'm not 100% sure about going code only. When I first started using it, there was something magic about click click click, you're done. We host it in Nomad, and it just works. Possibly again agree with @mikestaub that someone else can maintain that.  In the Asterisk community, we had APIs that made it possible for many other pieces to be built.

I do wonder though, with such a small surface area, whether it would even make sense to expose the api via api 😂 

Couldn't we just throw something together in tailwind in an afternoon and call it good?
4. We host a docker image in nomad. However, it really depends on who the target audience is, right? Like most people who use it are probably trying to avoid learning or using oAuth and are looking for a prepackaged solution.  

If it helps the project to remain liquid, I'm all for it.

Regarding @Simcon comment, I think you could basically do it like vscode no? Provide a skeleton of the most commonly used features via a UI and let people configure the underlying code if they see fit

**Comment by bastienbeurier** [comment]
Thanks a lot for voicing your opinions about Pizzly’s future (here and on the [#pizzly Slack channel](https://nango.dev/slack)). There seems to be a pretty nice consensus around important features.

Last week, we started a full rewrite of Pizzly on a branch ([v0.3](https://github.com/NangoHQ/Pizzly/tree/v0.3)) to make the code more maintainable and accelerate future development. It already works, and supports:
- OAuth 1 & 2
- a Docker container for the Pizzly server
- a CLI to configure integrations
- a Node SDK + REST API to fetch fresh tokens
- a frontend SDK to initiate OAuth flows

During the past week, you expressed interest in the following additional features:
- Proxy server for API requests
- A free 1-click deployment solution (Heroku is no longer free)
- In-code (versioned) configuration (additionally to the CLI)

The new Pizzly is also currently missing:
- An API key to secure Pizzly
- More logs and friendly error outputs
- Better comments in the code
- Tests
- More integrations (currently has 25 but we will quickly backfill + add new ones)

We would love to have you involved in building these features, or others that you have in mind. If you are interested, please let us know what you would like to take on. And if you have additional/different thoughts, please share them here or on the [#pizzly Slack channel](https://nango.dev/slack).

We want to quickly get to feature parity with the old Pizzly so that we can start making nice improvements!
